trigger:
- master
jobs:

- job: backend
  steps:
  - task: Docker@2
    displayName: Backend Docker image
    inputs:
      containerRegistry: 'babodesi'
      command: buildAndPush
      repository: 'babodesi/mern-backend'
      Dockerfile: '$(Build.SourcesDirectory)/trainee_backend/Dockerfile'
      tags: latest
      
- job: frontend
  dependsOn: backend
  steps:
  - task: Docker@2
    displayName: Frontend Docker image
    inputs:
      containerRegistry: 'babodesi'
      command: buildAndPush
      repository: 'babodesi/mern-frontend'
      Dockerfile: '$(Build.SourcesDirectory)/trainee_frontend/Dockerfile'
      tags: latest