trigger:
- master
jobs:

- job: backend
  steps:
  - task: Docker@2
    displayName: Backend Docker image
    inputs:
      command: buildAndPush
      Dockerfile: '$(Build.SourcesDirectory)/trainee_backend/Dockerfile'
      repository: babodesi/mern-backend
      tags: $(Build.BuildNumber)
      
- job: frontend
  dependsOn: backendend
  steps:
  - task: Docker@2
    displayName: Frontend Docker image
    inputs:
      command: buildAndPush
      repository: babodesi/mern-frontend
      Dockerfile: '$(Build.SourcesDirectory)/trainee_frontend/Dockerfile'
      tags: $(Build.BuildNumber)