trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'gujarat'
  dockerHubRepository: 'babodesi'
  dockerHubUsername: $(DOCKERHUB_USERNAME)
  dockerHubPassword: $(DOCKERHUB_PASSWORD)

steps:
- task: Docker@2
  displayName: 'Build and push Docker image'
  inputs:
    command: 'buildAndPush'
    containerRegistry: 'dockerHub'
    repository: '$(dockerHubRepository)'
    dockerfile: 'Dockerfile'
    tags: |
      $(Build.BuildNumber)
      latest
  env:
    DOCKERHUB_USERNAME: $(dockerHubUsername)
    DOCKERHUB_PASSWORD: $(dockerHubPassword)