trigger:
- master

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        command: 'login'
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'mern-backend'
        command: 'buildAndPush'
        Dockerfile: '**/trainee_backend'
        tags: '$(Build.BuildNumber)'
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'mern-frontend'
        command: 'buildAndPush'
        Dockerfile: '**/trainee_frontend'
        tags: '$(Build.BuildNumber)'