trigger:
- master

resources:
- repo: self

variables:
  dockerHubRepository: 'babodesi/mern'
  dockerHubUsername: 'babodesi'
  dockerHubPassword: 'ankit@2002'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Front-End image
      inputs:
        containerRegistry: 'dockerHub'
        repository: 'babodesi/gujarat'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/trainee_frontend/Dockerfile'
        buildContext: 'docker build . -t babodesi/mern-frontend'
        tags: '$(Build.BuildNumber) latest'
    - task: Docker@2
      displayName: Build Back-End image
      inputs:
        containerRegistry: 'dockerHub'
        repository: '$(dockerHubRepository)'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/trainee_backend/Dockerfile'
        buildContext: 'docker build . -t mern-backend'
        tags: '$(Build.BuildNumber) latest'