trigger:
- master

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        command: 'login'
    - task: Docker@2
      displayName: Build Front-End image
      inputs:
        containerRegistry: 'dockerHub'
        repository: 'babodesi/mern-frontend'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/trainee_frontend/Dockerfile'
        buildContext: 'docker build . -t babodesi/mern-frontend'
        tags: '$(Build.BuildNumber) latest'
    - task: Docker@2
      displayName: Build Back-End image
      inputs:
        containerRegistry: 'dockerHub'
        repository: 'babodesi/mern-backend'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/trainee_backend/Dockerfile'
        buildContext: 'docker build . -t mern-backend'
        tags: '$(Build.BuildNumber) latest'