trigger:
- master

resources:
- repo: self

variables:
  dockerHubRepository: 'babodesi/gujarat'
  dockerHubUsername: 'babodesi'
  dockerHubPassword: $(DOCKERHUB_PASSWORD)

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: 'buildAndPush'
        dockerfile: '$(Build.SourcesDirectory)/trainee_frontend/Dockerfile'
        tags:
          $(Build.BuildNumber)
          latest
        containerRegistry: 'dockerHub'
        repository: '$(dockerHubRepository)'
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: 'buildAndPush'
        dockerfile: '$(Build.SourcesDirectory)/trainee_backend/Dockerfile'
        tags:
          $(Build.BuildNumber)
          latest
        containerRegistry: 'dockerHub'
        repository: '$(dockerHubRepository)'

      env:
        DOCKERHUB_USERNAME: $(dockerHubUsername)
        DOCKERHUB_PASSWORD: $(dockerHubPassword)