trigger:
- master

jobs:
- job: frontend
  steps:
  - task: Docker@2
    displayName: Frontend
    inputs:
      command: buildAndPush
      Dockerfile: $(Build.SourcesDirectory)/trainee_frontend/Dockerfile
      repository: babodesi/mern-frontend
      tags: latest

- job: backend
  steps:
  - task: Docker@2
    displayName: Backend
    inputs:
      command: buildAndPush
      Dockerfile: $(Build.SourcesDirectory)/trainee_backend/Dockerfile
      repository: babodesi/mern-frontend
      tags: latest