trigger:
- master

jobs:
- job: frontend
  steps:
  - task: Docker@2
    displayName: Build Docker Image
    inputs:
      command: buildAndPush
      Dockerfile: $(Build.SourcesDirectory)/trainee_frontend/Dockerfile
      repository: babodesi/mern-frontend
      tags: latest

- job: backend
  dependsOn: Build
  steps:
  - task: Docker@2
    displayName: Push Docker Image
    inputs:
      command: buildAndPush
      Dockerfile: $(Build.SourcesDirectory)/trainee_backend/Dockerfile
      repository: babodesi/mern-frontend
      tags: latest