trigger:
- master
jobs:
- job: login
  steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        command: 'login'

- job: frontend
  dependsOn: login
  steps:
  - task: Docker@2
    displayName: Frontend Docker image
    inputs:
      command: buildAndPush
      Dockerfile: '$(Build.SourcesDirectory)/trainee_frontend/Dockerfile'
      repository: $(Build.RepositoryName)
      tags: $(Build.BuildNumber)

- job: backend
  dependsOn: frontend
  steps:
  - task: Docker@2
    displayName: Backend Docker image
    inputs:
      command: buildAndPush
      Dockerfile: '$(Build.SourcesDirectory)/trainee_backend/Dockerfile'
      repository: $(Build.RepositoryName)
      tags: $(Build.BuildNumber)