version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017

  backend:
    image: babodesi/mern-backend
    container_name: backend
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - mongodb