version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
  backend:
    build: 
      dockerfile: Dockerfile
      context: ./trainee_backend/
    container_name: backend
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
  frontend:
    build:   
      dockerfile: Dockerfile
      context: ./trainee_frontend/
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend