version: "3.9"
services:
  
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    networks:
      - backend-network
    ports:
      - 27017
  
  backend:
    build: 
      dockerfile: Dockerfile
      context: ./trainee_backend/
    container_name: backend
    image: mern-backend:v1
    restart: always
    ports:
      - 4000
    networks:
      - frontend-network
      - backend-network
    depends_on:
      - mongodb
  
  frontend:
    build:   
      dockerfile: Dockerfile
      context: ./trainee_frontend/
    image: mern-frontend:v1
    container_name: frontend
    restart: always 
    networks:
      - frontend-network
    ports:
      - 80:80
    depends_on:
      - backend

networks:
  frontend-network:
  backend-network: